include:
  - project: 'BungaaFACE/home_lab'
    file: 
      - 'pipeline-includes/templates.yml'
      - 'pipeline-includes/common_dirs.yml'

stages:
  - build
  - deploy
  - misc

build_repo_coppier:
  tags:
    - shell
  stage: build
  script:
    - docker build -f deploy/repo-coppier.dockerfile -t localhost:5000/repo-coppier:latest .
    - docker push localhost:5000/repo-coppier:latest
  when: manual
  allow_failure: true

deploy_repo_coppier:
  extends: .compose_deploy_template
  variables:
    COMPOSE_FILE: "deploy/compose-repo-coppier.yaml"

sync:
  tags:
    - shell
  stage: misc
  script:
    - docker compose -f ${COMPOSE_PATH}/compose-repo-coppier.yaml up --force-recreate
  when: manual
  allow_failure: true