include:
  - project: 'BungaaFACE/home-lab'
    file: 
      - 'pipeline-includes/templates.yml'
      - 'pipeline-includes/common_dirs.yml'

stages:
  - build
  - deploy
  - misc

build_repo_coppier:
  tags:
    - shell
  stage: build
  script:
    - docker build -f deploy/repo-coppier.dockerfile -t localhost:5000/repo-coppier:latest .
    - docker push localhost:5000/repo-coppier:latest
  when: manual
  allow_failure: true

deploy_repo_coppier:
  extends: .compose_deploy_template
  before_script:
    - cp $repositories_json ${DATA_PATH}/repo-coppier/repositories.json
  variables:
    COMPOSE_FILE_DIR: "deploy/"
    COMPOSE_FILE: "compose-repo-coppier.yaml"

sync:
  tags:
    - shell
  stage: misc
  script:
    - docker compose -f ${COMPOSE_PATH}/compose-repo-coppier.yaml up --force-recreate
  when: manual
  allow_failure: true