include:
  - project: 'BungaaFACE/home-lab'
    file: 
      - 'pipeline-includes/templates.yml'
      - 'pipeline-includes/common_dirs.yml'

stages:
  - build
  - deploy
  - misc

build_repo_coppier:
  tags:
    - shell
  stage: build
  needs: []
  script:
    - docker build -f deploy/repo-coppier.dockerfile -t localhost:5000/repo-coppier:latest .
    - docker push localhost:5000/repo-coppier:latest
  rules:
    - if: $TRIGGER_ACTION == $CI_JOB_NAME
    - when: manual

deploy_repo_coppier:
  extends: .compose_deploy_template
  needs: []
  before_script:
    - mkdir -p ${DATA_PATH}/repo-coppier
    - cp ${repositories_json} ${DATA_PATH}/repo-coppier/repositories.json
  variables:
    COMPOSE_FILE_DIR: "deploy/"
    COMPOSE_FILE: "compose-repo-coppier.yaml"
  rules:
    - if: $TRIGGER_ACTION == $CI_JOB_NAME
    - when: manual

sync_repo_coppier:
  tags:
    - shell
  stage: misc
  needs: []
  script:
    - docker compose -f ${COMPOSE_PATH}/compose-repo-coppier.yaml up --force-recreate
  rules:
    - if: $TRIGGER_ACTION == $CI_JOB_NAME
    - when: manual